ecommerce/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path

from ecommerce import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path

from shop import views
app_name = "shop"

urlpatterns = [
    path('', views.home, name="home"),
    path('product/<slug>', views.details, name="detail"),
    path('review/<slug>/post', views.review, name="review"),
    path('signup/', views.signup, name="signup"),
    path('login/', views.mylogin, name="login"),
    path('logout/', views.mylogout, name="logout"),
    path('search/', views.product_search, name="search"),
    path('add_to_cart/', views.add_to_cart, name="add_to_cart"),
    path('my_cart/', views.my_cart, name="my_cart"),
    path('checkout/', views.checkout, name="checkout"),
    path('category/<slug>/', views.categories, name="category"),
    path('products/', views.products, name="products"),
    path('api/products/', views.api_products, name="api_products"),

]

shop/models.py
# Create your models here.
from autoslug import AutoSlugField
from django.contrib.auth.models import User
from django.db import models


class Category(models.Model):
    title = models.CharField(max_length=200)
    slug = AutoSlugField(populate_from='title')
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to="categories", blank=True)
    featured = models.BooleanField(default=False)
    active = models.BooleanField(default=True)

    class Meta:
        verbose_name_plural = "Categories"
        ordering = ["title"]

    def __str__(self):
        return self.title


class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    slug = AutoSlugField(populate_from='title')
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to="products", blank=True)
    featured = models.BooleanField(default=False)
    active = models.BooleanField(default=True)
    brand = models.CharField(max_length=200, blank=True)
    shipping = models.TextField(blank=True)
    price = models.DecimalField(default=0, decimal_places=2, max_digits=10)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-created"]

    def __str__(self):
        return self.title


class Review(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    rate = models.IntegerField(default=5)
    review = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.review

shop/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from shop.models import Review


class ReviewForm(forms.ModelForm):
    def clean_rate(self):
        data = self.cleaned_data.get("rate", 5)
        if data < 0 or data > 5:
            raise forms.ValidationError("rate must be within range 1 to 5")
        return data

    class Meta:
        model = Review
        fields = ["rate", "review"]


class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]

shop/views.py
from django.contrib.auth import authenticate, login, logout
from django.db.models import Q
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404

# Create your views here.
from rest_framework.decorators import api_view
from rest_framework.response import Response

from shop.forms import SignUpForm, ReviewForm
from shop.models import Category, Product, Review
from shop.serializers import ProductSerializer


def get_payload(request, title=""):
    return {
        "title": title,
        "categories": Category.objects.filter(active=True),
        "carts": Product.objects.filter(slug__in=request.session.get('items', []))
    }


def home(request):
    data = get_payload(request, "Home")
    data["products"] = Product.objects.filter(active=True)
    return render(request, "shop/index.html", data)


def details(request, slug):
    product = get_object_or_404(Product, slug=slug)
    data = get_payload(request, product.title)
    data["product"] = product
    data["reviewform"] = ReviewForm()
    return render(request, "shop/details.html", data)


def review(request, slug):
    product = get_object_or_404(Product, slug=slug)
    if request.user.is_authenticated and request.method == "POST":
        form = ReviewForm(request.POST)
        if form.is_valid():
            review = form.save(commit=False)
            review.product = product
            review.user = request.user
            review.save()
        return redirect('shop:detail', product.slug)
    else:
        form = SignUpForm()
        return render(request, "shop/signup.html", {"form": form})


def signup(request):
    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.save()
            return redirect('shop:login')
    else:
        form = SignUpForm()
    return render(request, "shop/signup.html", {"form": form})


def mylogin(request):
    if request.user.is_authenticated:
        return redirect("shop:home")
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(username=username, password=password)
        if user:
            login(request, user)
            if user.is_active:
                return redirect("shop:home")
    return render(request, "shop/login.html")


def mylogout(request):
    logout(request)
    return redirect("shop:home")


def product_search(request):
    query = request.GET.get("q", "")
    data = get_payload(request, query + " - search result")
    data["products"] = Product.objects.filter(Q(title__contains=query) | Q(description__contains=query))
    return render(request, 'shop/products.html', data)


def my_cart(request):
    data = get_payload(request, "My cart")
    data["products"] = Product.objects.filter(slug__in=request.session.get('items', []))
    return render(request, 'shop/products.html', data)


def checkout(request):
    request.session['items'] = []
    request.session['cart_amount'] = 0
    return redirect("shop:home")


def categories(request, slug):
    category = get_object_or_404(Category, slug=slug)
    data = get_payload(request, category.title)
    data["products"] = Product.objects.filter(category=category)
    return render(request, "shop/products.html", data)


def products(request):
    data = get_payload(request, "Products")
    data["products"] = Product.objects.filter(active=True)
    return render(request, "shop/products.html", data)


def add_to_cart(request):
    if request.method == 'POST':
        slug = request.POST.get("slug", "")
        product = Product.objects.filter(slug=slug).first()
        if product:
            items = request.session.get('items', [])
            if slug not in items:
                items.append(product.slug)
                amount = request.session.get('cart_amount', 0.0) + float(product.price)
                request.session['items'] = items
                request.session['cart_amount'] = amount
                return JsonResponse({"status": "ok", "message": product.title + " added to cart",
                                     "count": len(items), "amount": amount})
            return JsonResponse({"status": "fail", "message": "Item already added"})
        return JsonResponse({"status": "fail", "message": "Item not found"})
    return JsonResponse({"status": "fail", "message": "Only post method allowed"})


@api_view(['GET'])
def api_products(request):
    query = request.GET.get("q", "")
    products = Product.objects.filter(Q(title__contains=query) | Q(description__contains=query))
    serializer = ProductSerializer(products, many=True)
    return Response(serializer.data)

shop/templates/shop/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="eCommerce project sample in django">
    <meta name="author" content="Hem Shrestha">

    <title>{% block title %}{{ title }}{% endblock %} - eCommerce Shop</title>
    <script src="/static/shop/js/jquery.min.js"></script>
    <link href="/static/shop/css/bootstrap.min.css" rel="stylesheet">
</head>

<body style="padding-top:56px">

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
        <a class="navbar-brand" href="/">eCommerce Shop</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'shop:products' %}">Products</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'shop:api_products' %}">API</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">My Account</a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        {% if user.is_authenticated %}
                            <a class="dropdown-item" href="{% url 'shop:my_cart' %}">My Cart</a>
                            <a class="dropdown-item" href="{% url 'shop:checkout' %}">Checkout</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'shop:logout' %}">Log Out</a>
                        {% else %}
                            <a class="dropdown-item" href="{% url 'shop:login' %}">Login</a>
                            <a class="dropdown-item" href="{% url 'shop:signup' %}">Signup</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'shop:checkout' %}">Checkout</a>
                        {% endif %}
                    </div>
                </li>
            </ul>

            <form class="form-inline my-2 my-lg-0 mr-4" action="{% url 'shop:search' %}">
                <input class="form-control mr-sm-2" name="q" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-primary my-2 my-sm-0" type="submit">Search</button>
            </form>

            <a href="{% url 'shop:my_cart' %}" class="btn btn-outline-success my-2 my-sm-0">
                <span class="glyphicon">🛒</span>
                <span id="cart_count">
                {% block cart_count %}
                    {% if carts|length == 0 %} No items
                    {% elif carts|length == 1 %} 1 item
                    {% else %} {{ carts|length }} items
                    {% endif %}
                {% endblock %}
                </span>
            </a>
        </div>
    </nav>

    <!-- Page Content -->
    <div class="container">
    {% block main_content %}
        <div class="row">
            <div class="col-lg-3">
                <h1 class="my-4">eCommerce Shop</h1>
                <div class="list-group">
                    {% block categories %}
                        {% for cat in categories %}
                            <a href="{% url 'shop:category' cat.slug %}" class="list-group-item">{{ cat.title }}</a>
                        {% endfor %}
                    {% endblock %}
                </div>
            </div>
            <div class="col-lg-9">
                {% block carousel %}{% endblock %}
                {% block content %}{% endblock %}
            </div>
        </div>
    {% endblock %}
    </div>

    <!-- Footer -->
    <footer class="py-5 bg-light">
        <div class="container">
            <p class="m-0 text-center">Copyright &copy; eCommerce Shop 2018</p>
        </div>
    </footer>

    <!-- JavaScripts -->
    <script src="/static/shop/js/bootstrap.min.js"></script>
    <script src="/static/shop/js/bootstrap.bundle.min.js"></script>
    {% block jscode %}{% endblock %}
</body>

</html>

shop/templates/shop/details.html
{% extends "shop/base.html" %}
{% load bootstrap4 %}

{% block content %}
    <div class="card mt-4">
            <img class="card-img-top img-fluid" src="/media/{{ product.image }}" alt="{{ product.title }}">
            <div class="card-body">
              <h3 class="card-title">{{ product.title }}</h3>
              <h4>Rs. {{ product.price }}</h4>
              <p class="card-text">{{ product.description }}</p>
              <span class="text-warning">&#9733; &#9733; &#9733; &#9733; &#9734;</span>
              4.0 stars
                <p></p>
                <p>
                    <a href="#" name="{{ product.slug }}" class="btn btn-success add_to_cart">Add to Cart</a>
                </p>
            </div>
          </div>
          <!-- /.card -->

          <div class="card card-outline-secondary my-4">
            <div class="card-header">
              Product Reviews
            </div>
            <div class="card-body">
                {% for rev in product.review_set.all %}
              <p>{{ rev.rate }} stars => {{ rev.review }}</p>
              <small class="text-muted">Posted by {{ rev.user }} on {{ rev.created }}</small>
              <hr>
                {% endfor %}
              <hr>
                <form method="POST" action="{% url "shop:review" product.slug %}">
                    {% csrf_token %}
                    {% bootstrap_form reviewform %}
                    <input type="submit" value="Submit your Review" class="btn btn-primary">

                </form>

            </div>
          </div>

{% endblock %}

{% block jscode %}
    <script>
        $(document).ready(function () {
            $('.add_to_cart').on('click', function () {
                data = {"slug": this.name, "csrfmiddlewaretoken":"{{ csrf_token }}" }
                $.post("{% url 'shop:add_to_cart' %}", data)
                    .done(function (response) {
                        if (response.status == "ok") {
                            $('#cart_count').text(response.count + " items");
                        }
                        alert(response.message);
                    })
            })
        })
    </script>
{% endblock %}

shop/templates/shop/index.html
{% extends "shop/base.html" %}

{% block carousel %}
          <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
            <ol class="carousel-indicators">
              <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
              <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
              <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner" role="listbox">
              <div class="carousel-item active">
                <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="First slide">
              </div>
              <div class="carousel-item">
                <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="Second slide">
              </div>
              <div class="carousel-item">
                <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="Third slide">
              </div>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="sr-only">Next</span>
            </a>
          </div>
{% endblock %}

{% block content %}
    <div class="row">
        {% for product in products %}
            <div class="col-lg-4 col-md-6 mb-4">
              <div class="card h-100">
                <a href="{% url 'shop:detail' product.slug %}">
                    <img class="card-img-top" src="/media/{{ product.image }}" alt="">
                </a>
                <div class="card-body">
                  <h4 class="card-title">
                    <a href="{% url 'shop:detail' product.slug %}">{{ product.title }}</a>
                  </h4>
                  <h5>Rs. {{ product.price }}</h5>
                  <p class="card-text">{{ product.description }}</p>
                </div>
                <div class="card-footer">
                  <small class="text-muted">&#9733; &#9733; &#9733; &#9733; &#9734;</small>
                </div>
              </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

shop/templates/shop/login.html
{% extends 'shop/base.html' %}
{% block main_content %}
    <div class="row">
        <div class="col-md-6 offset-3">
            <form method="post">
                {% csrf_token %}
                <p>Username</p><p><input name="username" placeholder="Username"></p>
                <p>Password</p><p></pp><input name="password" type="password" placeholder="Password"></p>
                <p><input class="btn btn-outline-info" type="submit" value="Log In"></p>
            </form>
        </div>
    </div>
{% endblock %}

shop/templates/shop/products.html
{% extends 'shop/base.html' %}

{% block content %}
        {% for p in products %}
            <div class="card mt-4 {% if forloop.last %}mb-4{% endif %}">
                <div class="row">
                    <div class="col-4">
                        <a href="{% url 'shop:detail' p.slug %}"><img src="/media/{{ p.image }}" class="img-fluid" alt="{{ p.title }}" ></a>
                    </div>
                    <div class="col">
                        <div class="card-block mt-4">
                            <h4 class="card-title"><a href="{% url 'shop:detail' p.slug %}">{{ p.title }}</a></h4>
                            <h5 class="card-text">{{ p.description }}</h5>
                            <p class="card-text">Rs. {{ p.price }}</p>
                            <a href="#" name="{{ p.slug }}" class="btn btn-success add_to_cart mb-4">Add to Cart</a>
                        </div>
                    </div>
                </div>
            </div>
        {% empty %}
            <div class="card mt-5">
                <div class="card-header">No data available</div>
            </div>
        {% endfor %}
{% endblock %}

{% block jscode %}
    <script>
        $(document).ready(function () {
            $('.add_to_cart').on('click', function () {
                data = {"slug": this.name, "csrfmiddlewaretoken":"{{ csrf_token }}" }
                $.post("{% url 'shop:add_to_cart' %}", data)
                    .done(function (response) {
                        if (response.status == "ok") {
                            $('#cart_count').text(response.count + " items");
                        }
                        alert(response.message);
                    });
            })
        })
    </script>
{% endblock %}

shop/templates/shop/signup.html
{% extends "shop/base.html" %}
{% load bootstrap4 %}
{% block main_content %}
    <div class="row">
        <div class="col-md-6 offset-3">
            <form method="POST">
                {% csrf_token %}
{#                {{ form }}#}
                {% bootstrap_form form %}
                <input class="btn btn-outline-info" type="submit" value="Signup">
            </form>
        </div>
    </div>
{% endblock %}